# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomdlint < Formula
  desc "Fast Markdown linter with autofix support"
  homepage "https://github.com/yaklabco/gomdlint"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaklabco/gomdlint/releases/download/v0.2.0/gomdlint_0.2.0_darwin_amd64.tar.gz"
      sha256 "fc3cdd5cb27d18642fc967a19c2159541d708780b9a20b65e5052165d87ebb8c"

      def install
        bin.install "gomdlint"
        bash_completion.install "completions/gomdlint.bash" => "gomdlint"
        zsh_completion.install "completions/gomdlint.zsh" => "_gomdlint"
        fish_completion.install "completions/gomdlint.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaklabco/gomdlint/releases/download/v0.2.0/gomdlint_0.2.0_darwin_arm64.tar.gz"
      sha256 "afff80d90511a39d0385b1bae2775d6e671e376e50265bcbb643bfa9da0f391f"

      def install
        bin.install "gomdlint"
        bash_completion.install "completions/gomdlint.bash" => "gomdlint"
        zsh_completion.install "completions/gomdlint.zsh" => "_gomdlint"
        fish_completion.install "completions/gomdlint.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/gomdlint/releases/download/v0.2.0/gomdlint_0.2.0_linux_amd64.tar.gz"
      sha256 "27b27d2f1972359cc10f9eed73dc88f47b6a648a0b7c4ef6e178acd3b80f36cc"
      def install
        bin.install "gomdlint"
        bash_completion.install "completions/gomdlint.bash" => "gomdlint"
        zsh_completion.install "completions/gomdlint.zsh" => "_gomdlint"
        fish_completion.install "completions/gomdlint.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/gomdlint/releases/download/v0.2.0/gomdlint_0.2.0_linux_arm64.tar.gz"
      sha256 "de97a1e968ae888c55d497e9f20b868aa99ae10b40613bff74982c2c2175e906"
      def install
        bin.install "gomdlint"
        bash_completion.install "completions/gomdlint.bash" => "gomdlint"
        zsh_completion.install "completions/gomdlint.zsh" => "_gomdlint"
        fish_completion.install "completions/gomdlint.fish"
      end
    end
  end

  test do
    system "#{bin}/gomdlint", "version"
  end
end
