# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gomdlint < Formula
  desc "Fast Markdown linter with autofix support"
  homepage "https://github.com/yaklabco/gomdlint"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaklabco/gomdlint/releases/download/v0.2.0/gomdlint_0.2.0_Darwin_x86_64.tar.gz"
      sha256 "ace9d6a2faf9f22335d97241c44a7b0bc58b1c52d7774ec520fc54a2f42bb9aa"

      def install
        bin.install "gomdlint"
        bash_completion.install "completions/gomdlint.bash" => "gomdlint"
        zsh_completion.install "completions/gomdlint.zsh" => "_gomdlint"
        fish_completion.install "completions/gomdlint.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaklabco/gomdlint/releases/download/v0.2.0/gomdlint_0.2.0_Darwin_arm64.tar.gz"
      sha256 "0ebc61fefe63ad47a664ba03600bf3b05643a50c262e1c29a9265bfa2cc61655"

      def install
        bin.install "gomdlint"
        bash_completion.install "completions/gomdlint.bash" => "gomdlint"
        zsh_completion.install "completions/gomdlint.zsh" => "_gomdlint"
        fish_completion.install "completions/gomdlint.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/gomdlint/releases/download/v0.2.0/gomdlint_0.2.0_Linux_x86_64.tar.gz"
      sha256 "11ace2448437f702c659c11ca60bc0618d1c3b4bd78c1c206686f5f3ded6bc4c"
      def install
        bin.install "gomdlint"
        bash_completion.install "completions/gomdlint.bash" => "gomdlint"
        zsh_completion.install "completions/gomdlint.zsh" => "_gomdlint"
        fish_completion.install "completions/gomdlint.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/gomdlint/releases/download/v0.2.0/gomdlint_0.2.0_Linux_arm64.tar.gz"
      sha256 "e3dd379a9d64cd89b387f320e2401375bd180a09343aaf9671c78c9016dc0cdd"
      def install
        bin.install "gomdlint"
        bash_completion.install "completions/gomdlint.bash" => "gomdlint"
        zsh_completion.install "completions/gomdlint.zsh" => "_gomdlint"
        fish_completion.install "completions/gomdlint.fish"
      end
    end
  end

  test do
    system "#{bin}/gomdlint", "version"
  end
end
