# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stave < Formula
  desc "Make(file) replacement that is pure Go based (a fork of `makefile/mage`)."
  homepage "https://github.com/yaklabco/stave"
  version "0.14.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaklabco/stave/releases/download/v0.14.2/stave_0.14.2_darwin_amd64.tar.gz"
      sha256 "e9427dee29914c8d4e8f25a0c0c245c3e409b5a18bbae2058b0e437bd59e83d6"

      define_method(:install) do
        bin.install "stave"
        bash_completion.install "completions/stave.bash" => "stave"
        zsh_completion.install "completions/stave.zsh" => "_stave"
        fish_completion.install "completions/stave.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaklabco/stave/releases/download/v0.14.2/stave_0.14.2_darwin_arm64.tar.gz"
      sha256 "bcb3d12a270f3b61c8cfc99e17769e876c21640645ddbb243edf80fa1e099184"

      define_method(:install) do
        bin.install "stave"
        bash_completion.install "completions/stave.bash" => "stave"
        zsh_completion.install "completions/stave.zsh" => "_stave"
        fish_completion.install "completions/stave.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/stave/releases/download/v0.14.2/stave_0.14.2_linux_amd64.tar.gz"
      sha256 "e7d41460defaeb25929bf9712e7369ec81047ace2ba930c429b3a8e2c65f7ede"
      define_method(:install) do
        bin.install "stave"
        bash_completion.install "completions/stave.bash" => "stave"
        zsh_completion.install "completions/stave.zsh" => "_stave"
        fish_completion.install "completions/stave.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/stave/releases/download/v0.14.2/stave_0.14.2_linux_arm.tar.gz"
      sha256 "a8c3120cd302afa1f49e6e5763650320b8336825f431ce1648d1fe0e0fa2b5f9"
      define_method(:install) do
        bin.install "stave"
        bash_completion.install "completions/stave.bash" => "stave"
        zsh_completion.install "completions/stave.zsh" => "_stave"
        fish_completion.install "completions/stave.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/stave/releases/download/v0.14.2/stave_0.14.2_linux_arm64.tar.gz"
      sha256 "61265f4042490bddd5d0ba27fbe63f18c25d354004035a4ce63666b10d8ae000"
      define_method(:install) do
        bin.install "stave"
        bash_completion.install "completions/stave.bash" => "stave"
        zsh_completion.install "completions/stave.zsh" => "_stave"
        fish_completion.install "completions/stave.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions, you may need to add the following to your shell profile, and then open a new shell:
        zsh:
          autoload -U compinit && compinit
        bash:
          [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/stave --version"
  end
end
