# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stave < Formula
  desc "Make(file) replacement that is pure Go based (a fork of `makefile/mage`)."
  homepage "https://github.com/yaklabco/stave"
  version "0.5.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaklabco/stave/releases/download/v0.5.3/stave_0.5.3_darwin_amd64.tar.gz"
      sha256 "d65c260f407fa81dc40aafd3ba9eb5beedbc5652bb8890c2bf049b93c5c4c960"

      def install
        bin.install "stave"
        bash_completion.install ".build_cache/completions/stave.bash" => "stave"
        zsh_completion.install ".build_cache/completions/stave.zsh" => "_stave"
        fish_completion.install ".build_cache/completions/stave.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaklabco/stave/releases/download/v0.5.3/stave_0.5.3_darwin_arm64.tar.gz"
      sha256 "9b0b8bd4162f0667b403a5c0862d9b598db54b2beadfc1f76725fef73a1e0050"

      def install
        bin.install "stave"
        bash_completion.install ".build_cache/completions/stave.bash" => "stave"
        zsh_completion.install ".build_cache/completions/stave.zsh" => "_stave"
        fish_completion.install ".build_cache/completions/stave.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/stave/releases/download/v0.5.3/stave_0.5.3_linux_amd64.tar.gz"
      sha256 "42bb8c35eb02b90973b57f6ed5c95387031ef28b51665e82888fdc131f52ded1"
      def install
        bin.install "stave"
        bash_completion.install ".build_cache/completions/stave.bash" => "stave"
        zsh_completion.install ".build_cache/completions/stave.zsh" => "_stave"
        fish_completion.install ".build_cache/completions/stave.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/stave/releases/download/v0.5.3/stave_0.5.3_linux_arm.tar.gz"
      sha256 "a225f4b5495be762f22acc7912d333a5e1b5f9bef37eca7e783c26f59bf513ba"
      def install
        bin.install "stave"
        bash_completion.install ".build_cache/completions/stave.bash" => "stave"
        zsh_completion.install ".build_cache/completions/stave.zsh" => "_stave"
        fish_completion.install ".build_cache/completions/stave.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/stave/releases/download/v0.5.3/stave_0.5.3_linux_arm64.tar.gz"
      sha256 "73ffef084f1d62e3a3b1b286fdcaa53ab9ad4bc22b364d3957a7532ae87ca08b"
      def install
        bin.install "stave"
        bash_completion.install ".build_cache/completions/stave.bash" => "stave"
        zsh_completion.install ".build_cache/completions/stave.zsh" => "_stave"
        fish_completion.install ".build_cache/completions/stave.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions, you may need to add the following to your shell profile, and then open a new shell:
        zsh:
          autoload -U compinit && compinit
        bash:
          [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/stave --version"
  end
end
