# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stave < Formula
  desc "Make(file) replacement that is pure Go based (a fork of `makefile/mage`)."
  homepage "https://github.com/yaklabco/stave"
  version "0.10.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaklabco/stave/releases/download/v0.10.7/stave_0.10.7_darwin_amd64.tar.gz"
      sha256 "ec34a7274c8d484124209cf61356f767189622189606a1c7cda2608d55e9a2a2"

      def install
        bin.install "stave"
        bash_completion.install "completions/stave.bash" => "stave"
        zsh_completion.install "completions/stave.zsh" => "_stave"
        fish_completion.install "completions/stave.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaklabco/stave/releases/download/v0.10.7/stave_0.10.7_darwin_arm64.tar.gz"
      sha256 "46ce33c351542a314904e846946fb1b5a27e060a60b0ec83307be550ff5f93c4"

      def install
        bin.install "stave"
        bash_completion.install "completions/stave.bash" => "stave"
        zsh_completion.install "completions/stave.zsh" => "_stave"
        fish_completion.install "completions/stave.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/stave/releases/download/v0.10.7/stave_0.10.7_linux_amd64.tar.gz"
      sha256 "571617e37b835856e20378b5e417cd45553427219e3f7a333fc1b63ad30b649b"
      def install
        bin.install "stave"
        bash_completion.install "completions/stave.bash" => "stave"
        zsh_completion.install "completions/stave.zsh" => "_stave"
        fish_completion.install "completions/stave.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/stave/releases/download/v0.10.7/stave_0.10.7_linux_arm.tar.gz"
      sha256 "0754124a45dc8ae0b2242d084cce06da1560b644d29ce6f839fd5f683adbf2f9"
      def install
        bin.install "stave"
        bash_completion.install "completions/stave.bash" => "stave"
        zsh_completion.install "completions/stave.zsh" => "_stave"
        fish_completion.install "completions/stave.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/stave/releases/download/v0.10.7/stave_0.10.7_linux_arm64.tar.gz"
      sha256 "e36bde3b2a2e89d65501b4cc05cbdd5c68e86f9851bdfc6f4b6cf5d353da3975"
      def install
        bin.install "stave"
        bash_completion.install "completions/stave.bash" => "stave"
        zsh_completion.install "completions/stave.zsh" => "_stave"
        fish_completion.install "completions/stave.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions, you may need to add the following to your shell profile, and then open a new shell:
        zsh:
          autoload -U compinit && compinit
        bash:
          [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/stave --version"
  end
end
