# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TldGetter < Formula
  desc "Check domain availability across TLDs"
  homepage "https://github.com/yaklabco/tld-getter"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaklabco/tld-getter/releases/download/v0.1.0/tld-getter_0.1.0_darwin_amd64.tar.gz"
      sha256 "118074db415e4273591b2e75e59cfa8c33cfb9e932628fc355b6318b16c45d6b"

      define_method(:install) do
        bin.install "tld-getter"
        bash_completion.install "completions/tld-getter.bash" => "tld-getter"
        zsh_completion.install "completions/tld-getter.zsh" => "_tld-getter"
        fish_completion.install "completions/tld-getter.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaklabco/tld-getter/releases/download/v0.1.0/tld-getter_0.1.0_darwin_arm64.tar.gz"
      sha256 "10dd2502c81f873a8a41648f64a254c8fedb001e54cfdee36a50e71c0c255475"

      define_method(:install) do
        bin.install "tld-getter"
        bash_completion.install "completions/tld-getter.bash" => "tld-getter"
        zsh_completion.install "completions/tld-getter.zsh" => "_tld-getter"
        fish_completion.install "completions/tld-getter.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/tld-getter/releases/download/v0.1.0/tld-getter_0.1.0_linux_amd64.tar.gz"
      sha256 "42fc4aeb252bb03897af1b2ac9b62e39a85633a59ca27133212afbb5ed223c90"
      define_method(:install) do
        bin.install "tld-getter"
        bash_completion.install "completions/tld-getter.bash" => "tld-getter"
        zsh_completion.install "completions/tld-getter.zsh" => "_tld-getter"
        fish_completion.install "completions/tld-getter.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/tld-getter/releases/download/v0.1.0/tld-getter_0.1.0_linux_arm64.tar.gz"
      sha256 "272877fc3fa5078deae0f4e413e5e58a40814f550ea28e47c336da619ed5812c"
      define_method(:install) do
        bin.install "tld-getter"
        bash_completion.install "completions/tld-getter.bash" => "tld-getter"
        zsh_completion.install "completions/tld-getter.zsh" => "_tld-getter"
        fish_completion.install "completions/tld-getter.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions, you may need to add the following to your shell profile, and then open a new shell:
        zsh:
          autoload -U compinit && compinit
        bash:
          [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/tld-getter --version"
  end
end
