# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./custom_download_strategy"
class Yak < Formula
  desc "CLI for the yaklab control plane — manage members, invitations, services, and audit logs."
  homepage "https://github.com/yaklabco/yaklab-controlplane"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.6.0/yak_0.6.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1a9c9542e200657f8a41e7ecf22330a506bbac30bfb0c71c39c2ccc1d241721d"

      define_method(:install) do
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.6.0/yak_0.6.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "402bd403cf0435997ad12870ba210f5670ef25d23df21ce196c4039ce5d95c32"

      define_method(:install) do
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.6.0/yak_0.6.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b43d34b0b580363880e855b642ecef63d5f51b9b70694944c35036c74a1d9985"
      define_method(:install) do
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.6.0/yak_0.6.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e2ac3cd3695e1a02208f94f94e3d4edbe4ceb72e86c451610084420cd410034f"
      define_method(:install) do
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions, you may need to add the following to your shell profile:
        fish: yak completion fish | source
        zsh:  autoload -U compinit && compinit
        bash: [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/yak", "version"
  end
end
