# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./custom_download_strategy"
class Yak < Formula
  desc "CLI for the yaklab control plane — manage members, invitations, services, and audit logs."
  homepage "https://github.com/yaklabco/yaklab-controlplane"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.5.0/yak_0.5.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "24094079b5ff01bffc04268fd1cdf3f6b742f404aa8f7b894f3302c5abbc5ca0"

      define_method(:install) do
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.5.0/yak_0.5.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "30d5587a525aa5fa82a69cf0917ca05837cdc3311a8b8c5a98f7c69cb14272bf"

      define_method(:install) do
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.5.0/yak_0.5.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8d4dffd8e72feea512c0e9931d0f4f44e7182a503b31238911a5957da0289301"
      define_method(:install) do
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.5.0/yak_0.5.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7815c00386c74f58b83eb3e1779c46cab243ff6a30fe0fc6a577d44d9bed967c"
      define_method(:install) do
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions, you may need to add the following to your shell profile:
        fish: yak completion fish | source
        zsh:  autoload -U compinit && compinit
        bash: [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/yak", "version"
  end
end
