# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "../custom_download_strategy"
class Yak < Formula
  desc "CLI for the yaklab control plane — manage members, invitations, services, and audit logs."
  homepage "https://github.com/yaklabco/yaklab-controlplane"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.1.0/yak_0.1.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "baa881d48add5c8f43d1e5e68eab944314c4e70764c495c99fe25d7fd4b2eb98"

      def install
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.1.0/yak_0.1.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f9bd29cddb94642da4f756e42a0d0237bc7ed8ddd63dd3ea841590fd9f8862b0"

      def install
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.1.0/yak_0.1.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bfcd1de291ff968066a20741067d84760288a10c61fd87b857257ac1f62a02f9"
      def install
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/yaklab-controlplane/releases/download/v0.1.0/yak_0.1.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "7234e668828f3fc14485afcfdba17e2aa0ad654d97b6b29f83e29697de0e276c"
      def install
        bin.install "yak"
        bash_completion.install "completions/yak.bash" => "yak"
        zsh_completion.install "completions/yak.zsh" => "_yak"
        fish_completion.install "completions/yak.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable completions, you may need to add the following to your shell profile:
        fish: yak completion fish | source
        zsh:  autoload -U compinit && compinit
        bash: [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
    EOS
  end

  test do
    system "#{bin}/yak", "version"
  end
end
