# This file was generated by GoReleaser. DO NOT EDIT.
cask "stave" do
  version "0.17.3"

  on_macos do
    on_arm do
      sha256 "ca25469b4b7039fec1b0da3fd82bef7c05f5a27f1841412f7cc921a1cf63dae7"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a305705751d4c96ecf14a9f982e500d9b7005b8336c94f8571508b3d070411f0"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e8cbc225cddcf83b2cc04be769cddf437b0d51a9c0ecca76902588dcc7670915"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "76d54cfdaf5bfeb80ac7e545acecad6aa37ab2044cee37e7d520d6f905e4ac65"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_linux_amd64.tar.gz"
    end
  end

  name "stave"
  desc "Make(file) replacement that is pure Go based (a fork of `makefile/mage`)."
  homepage "https://github.com/yaklabco/stave"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stave"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stave"]
    end
  end
  generate_completions_from_executable "stave",
    shell_parameter_format: :cobra

  # No zap stanza required

  caveats <<~EOS
    If you previously installed stave via homebrew formulas, please run:
      brew uninstall yaklabco/tap/stave

    To enable completions, you may need to add the following to your shell profile, and then open a new shell:
      zsh:
        autoload -U compinit && compinit
      bash:
        [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
  EOS
end
