# This file was generated by GoReleaser. DO NOT EDIT.
cask "stave" do
  version "0.16.6"

  on_macos do
    on_intel do
      sha256 "85a7fddae3b1b7d05f5e966bed2af9e27fd53567384370ae206d4f329b320385"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "14002345767b2c46886503b05661e80fa8ea50abecac3a2e4dd40a0e2b77accb"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "01e0148af1c0a770fc889389351d11e32a5a4e4b97773d5de90009e133c37676"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9cf630aa4fe53dfd3f836c7523b5e61a042bb8c2d897532ac3fe996056f8211e"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stave"
  desc "Make(file) replacement that is pure Go based (a fork of `makefile/mage`)."
  homepage "https://github.com/yaklabco/stave"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stave"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stave"]
    end
  end
  generate_completions_from_executable "stave",
    shell_parameter_format: :cobra

  # No zap stanza required

  caveats <<~EOS
    If you previously installed stave via homebrew formulas, please run:
      brew uninstall yaklabco/tap/stave

    To enable completions, you may need to add the following to your shell profile, and then open a new shell:
      zsh:
        autoload -U compinit && compinit
      bash:
        [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
  EOS
end
