# This file was generated by GoReleaser. DO NOT EDIT.
cask "stave" do
  version "0.14.16"

  on_macos do
    on_intel do
      sha256 "78d710c23cffa05597f4711cea9ee310e4f2775355911e7dd5ac7d979b7c9f7f"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2937f8787d4e9f9d18d7bfa7801bd0c9739017845621cb90f38bc5f119c09d13"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a9f200388886696dd0e9f4a4009d90c1c41bd39c9e13310e592731e2eded3b70"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "62c1696757a98869a5873010e3aa193de5e3ff104c174ce482ac9d97734325fb"
      url "https://github.com/yaklabco/stave/releases/download/v#{version}/stave_#{version}_linux_arm64.tar.gz"
    end
  end

  name "stave"
  desc "Make(file) replacement that is pure Go based (a fork of `makefile/mage`)."
  homepage "https://github.com/yaklabco/stave"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "stave"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/stave"]
    end
  end
  generate_completions_from_executable "stave",
    shell_parameter_format: :cobra

  # No zap stanza required

  caveats <<~EOS
    If you previously installed stave via homebrew formulas, please run:
      brew uninstall yaklabco/tap/stave

    To enable completions, you may need to add the following to your shell profile, and then open a new shell:
      zsh:
        autoload -U compinit && compinit
      bash:
        [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"
  EOS
end
