# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dot < Formula
  desc "Type-safe symbolic link manager for dotfiles"
  homepage "https://github.com/yaklabco/dot"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yaklabco/dot/releases/download/v0.7.0/dot_0.7.0_Darwin_x86_64.tar.gz"
      sha256 "cdd6f5d2ed3d6190ee50abcbf8f45a9e54ee7ac2285df78dc0629e02c8e9f688"

      def install
        bin.install "dot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yaklabco/dot/releases/download/v0.7.0/dot_0.7.0_Darwin_arm64.tar.gz"
      sha256 "3618c0f65bb3bc54dc78cce0d2dcb056054dc9df1afe36f686b8179fd989e025"

      def install
        bin.install "dot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/dot/releases/download/v0.7.0/dot_0.7.0_Linux_x86_64.tar.gz"
      sha256 "b0155f73735082d8b9c888e7650d46d406d645da96118b4a9085bf185f377672"
      def install
        bin.install "dot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yaklabco/dot/releases/download/v0.7.0/dot_0.7.0_Linux_arm64.tar.gz"
      sha256 "4cbadb0a8250f7192a35f0e5d9f7fb573f06039b87db6a95d5673999691b9a70"
      def install
        bin.install "dot"
      end
    end
  end

  def caveats
    <<~EOS
      dot manages configuration files through symbolic links.

      Configuration file location (XDG Base Directory):
        $XDG_CONFIG_HOME/dot/config.yaml
        or ~/.config/dot/config.yaml

      Basic usage:
        dot manage <package>    # Install package
        dot status             # Show package status
        dot unmanage <package>  # Remove package

      Documentation: https://github.com/yaklabco/dot
    EOS
  end

  test do
    system "#{bin}/dot", "--version"
    system "#{bin}/dot", "--help"
  end
end
